# air.toml

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  
  delay = 1000
  stop_on_error = false
  send_interrupt = true
  kill_delay = "500ms"
  
[log]
  time = true

[misc]
  clean_on_exit = true
